tap "datawire/blackbird"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mveritym/mel"
tap "osx-cross/arm"
brew "ack"
brew "openssl"
brew "asdf"
brew "bash"
brew "ghc"
brew "cabal-install"
brew "python"
brew "ctags"
brew "curl"
brew "dfu-util"
brew "dnsmasq", restart_service: true
brew "docker-machine-driver-xhyve"
brew "exercism"
brew "fleetctl"
brew "fzf"
brew "gnupg", link: false
brew "go"
brew "gotags"
brew "graphviz"
brew "hopenpgp-tools"
brew "htop"
brew "httpie"
brew "jq"
brew "kubernetes-cli", link: false
brew "kubernetes-helm"
brew "libuv"
brew "macvim"
brew "mas"
brew "midnight-commander"
brew "mongodb", restart_service: true
brew "ncdu"
brew "nmap"
brew "node"
brew "ntfs-3g"
brew "pass"
brew "pgcli"
brew "pinentry-mac"
brew "pipenv"
brew "postgresql"
brew "ranger"
brew "socat"
brew "sphinx-doc"
brew "telnet"
brew "testdisk"
brew "the_silver_searcher"
brew "tig"
brew "tldr"
brew "tmux"
brew "watch"
brew "xhyve", args: ["HEAD"]
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
brew "mveritym/mel/kubedecode"

cask "osxfuse"
cask "1password-cli"
cask "calibre"
cask "font-inconsolata"
cask "font-terminus"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "java8"
cask "private-eye"
cask "virtualbox"

mas "HyperDock", id: 449830122
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
